name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      # Checkout full history (needed for gh-pages deployment)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Julia setup
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'
      - uses: julia-actions/cache@v1

      - name: Install PlutoBoardExamples beforehand to avoid issues with non registered repo
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(url="https://github.com/UniStuttgart-IKR/PlutoBoardExamples"))'

      - name: Install Julia dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      - name: Build Julia docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs/ docs/make.jl

      # JS docs build

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install JS dependencies
        working-directory: docs
        run: |
          npm i

      - name: Generate JS docs
        working-directory: docs
        run: npx jsdoc --configure jsdoc.json


      # Deploy JS docs to gh-pages (only on main repo)
      - name: Deploy JS docs to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin gh-pages

          # Use worktree to avoid dirty working directory
          git worktree add gh-pages-worktree gh-pages

          # Copy JS docs into worktree
          rm -rf gh-pages-worktree/docs/js
          mkdir -p gh-pages-worktree/docs/js
          cp -r docs/js/* gh-pages-worktree/docs/js/

          cd gh-pages-worktree
          git add docs/js
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update JS docs"
            git push origin gh-pages
          fi

          # Clean up
          cd ..
          git worktree remove gh-pages-worktree --force
